services:
  - type: web
    name: iptv-panel
    runtime: python
    repo: https://github.com/josieljefferson/iptv-panel
    branch: main
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: SECRET_KEY
        generateValue: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.auth:app
    healthCheckPath: /api/status
    autoDeploy: true